-- Maison de Luxe POS — initial schema
-- Tuned for the existing localStorage data model so browser data can
-- sync cleanly into Postgres (identity columns use BY DEFAULT so the
-- client can replay its own ids).

-- ---------------------------------------------------------------------------
-- Staff profiles (extends Supabase auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'cashier' check (role in ('cashier', 'manager')),
  name text not null default '',
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Menu catalog (mirrors src/data/menu.js plus live stock levels)
-- ---------------------------------------------------------------------------
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Orders + line items
-- ---------------------------------------------------------------------------
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  order_type text not null default 'Dine-in',
  sub_total numeric(10, 2) not null default 0,
  discount_amount numeric(10, 2) not null default 0,
  discount_label text not null default '',
  tax_amount numeric(10, 2) not null default 0,
  total_amount numeric(10, 2) not null default 0,
  payment_method text not null check (
    payment_method in ('Credit Card', 'Paylater', 'Cash Payout', 'GCash', 'Maya')
  ),
  order_status text not null default 'Pending' check (
    order_status in ('Pending', 'Completed', 'Cancelled')
  ),
  cash_tendered numeric(10, 2),
  change_amount numeric(10, 2),
  cashier_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id) on delete cascade,
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  subtotal numeric(10, 2) not null check (subtotal >= 0)
);

create index if not exists order_items_order_id_idx on public.order_items (order_id);

-- ---------------------------------------------------------------------------
-- Customers (loyalty tiers — roadmap feature #9)
-- ---------------------------------------------------------------------------
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text not null default '',
  email text not null default '',
  visits integer not null default 0 check (visits >= 0),
  total_spent numeric(12, 2) not null default 0 check (total_spent >= 0),
  tier text not null default 'Bronze' check (tier in ('Bronze', 'Silver', 'Gold', 'Platinum')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Settings (restaurant name / contact / address etc.)
-- ---------------------------------------------------------------------------
create table if not exists public.settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
  before update on public.menu_items
  for each row execute function public.set_updated_at();

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
  before update on public.customers
  for each row execute function public.set_updated_at();

drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at
  before update on public.settings
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- API access: "automatically expose new tables" is OFF in the dashboard,
-- so grant the authenticated role explicit access here (the anon role gets
-- nothing — every API call must come from a logged-in staff member).
-- ---------------------------------------------------------------------------
grant usage on schema public to authenticated;
grant select, insert, update, delete on
  public.profiles,
  public.menu_items,
  public.orders,
  public.order_items,
  public.customers,
  public.settings
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.customers enable row level security;
alter table public.settings enable row level security;

-- Profiles: any staff member can read profiles; you may create your own.
create policy "profiles_select" on public.profiles
  for select using (auth.role() = 'authenticated');
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

-- Business data (menu, orders, customers, settings): any logged-in staff
-- member — matches the app where cashiers and the manager share one register.
create policy "menu_all_authenticated" on public.menu_items
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "orders_all_authenticated" on public.orders
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "order_items_all_authenticated" on public.order_items
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "customers_all_authenticated" on public.customers
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "settings_all_authenticated" on public.settings
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');